### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by iGetUploaded** [TheLazySquid/DiscordGifCaptioner#1]
Why is there Base64 in the file?

**Comment by TheLazySquid** [comment]
That's the futura bold condensed font that the caption uses. This script uses @wemap/rollup-plugin-arraybuffer to automatically convert the font into an ArrayBuffer which is passed into a [font face](https://developer.mozilla.org/en-US/docs/Web/API/FontFace/FontFace) to load the font without any external dependencies.
