### ISSUE TITLE
Wrong font

### ISSUE THREAD

**Issue by DoritoTheChips** [TheLazySquid/DiscordGifCaptioner#10]
The font used in the plugin is the wrong one.

The font used by iFunny - which is the most popular one - is the **Futura Condensed Extra Bold** :
![image](https://github.com/user-attachments/assets/c1bf0863-aa63-40ca-999d-93b9678c3929)

However the font used in the plugin is the **Futura Condensed Bold** which does not correspond to the one used by iFunny:
![image](https://github.com/user-attachments/assets/3d8bd8b0-300a-404e-9023-fab325d09f1e)

I can provide you the correct font file you need.

**Comment by TheLazySquid** [comment]
Good catch! v0.2.2 now uses the extra bold version of the font.
