### ISSUE TITLE
Support for image gifs

### ISSUE THREAD

**Issue by vilewired** [TheLazySquid/DiscordGifCaptioner#11]
I saw that a few gifs I have don't have the cc button over them. Found the gif selector and changed it to this:
```js
const gifSelector = "video[class^='gif'], img[class^='gif']";
```

and the width from the img gif you can get from the natural width I think:
```js
if (gif.tagName === "VIDEO") {
          nwidth = gif.videoWidth;
        } else if (gif.tagName === "IMG") {
          nwidth = gif.naturalWidth;}
```

but I don't know much about react and js so I cannot change everything in the plugin to maybe support img. I was wondering if img[class^='gif'] could be supported. I really like the plugin and think this would make for an awesome addition!

**Comment by TheLazySquid** [comment]
Was the button missing from gifs that had been uploaded manually and then favorited? If so, supporting them will take some effort. "Gifs" from tenor are actually just videos, which makes them easy to work with, but I can imagine that a raw gif would be somewhat harder to work with.

**Comment by vilewired** [comment]
Yeah the gifs saved from tenor are "video" gifs. But those saved for example on the discord cdn are usually of the type "image" so there's about 70% of gifs missing. As I said I found a way already to also find those gifs and sort them. I just don't know how to do the rest. Btw your website is insanely funny, had a lot of fun looking around on it

**Comment by TheLazySquid** [comment]
Alright, this should now be added! You'll need to download it from here until the update is accepted by BetterDiscord.

**Comment by vilewired** [comment]
Yeah tysm for adding this. Can I add you on discord?

**Comment by TheLazySquid** [comment]
Sure, I'm @thelazysquid.
