### ISSUE TITLE
Issue: Gif not being added to message

### ISSUE THREAD

**Issue by NostalJack** [TheLazySquid/DiscordGifCaptioner#5]
It could be just me, however it seems after being rendered the gif no longer gets put into the message. Not sure what could have changed or if its an addon.

Thank you for this as well, it makes things so much easier in the meme department

**Comment by TheLazySquid** [comment]
I've seen this happen once before, try switching channels or restarting discord. If it consistently happens tell me, but I'll probably take a bit to get back to you due to school.

**Comment by NostalJack** [comment]
Thank you for the quaint reply. You where absolutely right. I will keep an eye out for if it happens constantly
