### ISSUE TITLE
Uploading wrong Gif ?

### ISSUE THREAD

**Issue by Lancaban** [TheLazySquid/DiscordGifCaptioner#7]
Ok not sure how to start, or troubleshoot as it might be on my end, but I'm not sure how.

2 separate times today, I searched for a GIF
clicked the little CC button, the preview pane there showed the correct GIF, I added my text, hit send.
Wait for the render, wait for the upload, and then a different GIF (but with the appropriate text) appeared.

I went to a private Chanel to do some testing, and I got many GIF's in a row to upland properly, then went back, the SAME GIF seems to cause the problem every time, but I'm not sure where to go from there.

I tried several other results, from the same search, and had no problem, so it seems to be that one specific GIF. Not sure if there is anything can be done about it. But I though best to report it anyway in case anyone else runs into a problem

**Comment by TheLazySquid** [comment]
Could you send the search and GIF that are causing these problems?

**Comment by Lancaban** [comment]
if you can tell me how to get the GIf URL out of discord on to here, I most certainly can :)

**Comment by TheLazySquid** [comment]
Just send a screenshot of what you searched and which GIF is causing the trouble

**Comment by Lancaban** [comment]
ok for me at least, it's a short scroll down and on the right, there's a couple similar but shorter GIF's near the top.
![Screenshot_20240819_180648](https://github.com/user-attachments/assets/a889eb2c-8756-47d4-bcfa-7211add43b29)

Sort of a play on the Hulk/Black-Widow GIF from a while back

**Comment by Lancaban** [comment]
Oh and I should mention, of the 3 times I tried it, it didn't keep pulling up the SAME wrong GIF, each time it pulled up a different one.

**Comment by TheLazySquid** [comment]
That gif seems to work fine for me- does the problem persist if you restart discord?

**Comment by Lancaban** [comment]
Ok.... it is now working fine...
sorry to have bothered you and taken up your time, Ii feel dumb lol

**Comment by TheLazySquid** [comment]
It's definitely my fault somehow, but I'm glad to hear it's working again

**Comment by Lancaban** [comment]
Nah man, you're good. You made an awesome plugin, I use it constantly. Thank you.

**Comment by Lancaban** [comment]
Sorry to re-eopen this (sort of)
but I had the same problem again today, and did some experimentation, the problem seems limited to a specific server.  Tried to caption a GIf, and it sent the wrong one, different GIF this time, but the same server had the issues,

the same GIf/caption went through properly in DM;'s and a few other servers.

So I don't think it's a problem with the plugin per-se, but I'm wondering what it is about that server that might be making it behave that way. 

I'm not sure how the GIF's are labeled internally, or how any given setting in the server would or wouldn't affect it. It seems to only happen once in a while, but always in that same server, and only in that particular server.

**Comment by TheLazySquid** [comment]
Weird. Is it re-sending a gif you already sent, or a completely random one?

**Comment by Lancaban** [comment]
Completely random, even if I try the same one a few times in a row, it will send a different "wrong" gif 
Again only that server and only rarely
It may be entirely not on your end but I thought I'd document here on the off chance anyone else runs into a problem 
***@***.***
 
My other Sites: 
***@***.***
Sent from Proton Mail Android
-------- Original Message --------On 8/26/24 6:26 PM, TheLazySquid  wrote:
Weird. Is it re-sending a gif you already sent, or a completely random one?

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you modified the open/close state.Message ID: ***@***.***>
[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/TheLazySquid/DiscordGifCaptioner/issues/7#issuecomment-2311213852",
"url": "https://github.com/TheLazySquid/DiscordGifCaptioner/issues/7#issuecomment-2311213852",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
