### ISSUE TITLE
New file size Limit

### ISSUE THREAD

**Issue by Lancaban** [TheLazySquid/DiscordGifCaptioner#9]
Discord recently reduced the upland limit to 10Mb without Nitro, causing the captioned GIFs to frequently fail

![Screenshot_20240924_121848](https://github.com/user-attachments/assets/486f6f0e-0d9e-4f77-a52b-4eae06a03da7)

**Comment by TheLazySquid** [comment]
All this required was tweaking a variable. The GIFs may be lower resolution now but hopefully they don't fail.

**Comment by Lancaban** [comment]
Thanks, I figured it would be pretty simple, but I wanted to make sure someone brought it up. :) 

Not all failed mind you, it obviously had a lot to do with the size of the original/source GIF .

again, great work on a great plug-in, thank you very much!
